import { randomUUID } from "node:crypto";
import { submitPublicInquiry } from "./actions";

type InquiryFormProps = { publicId: string; active: boolean };
const inputClass = "rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-[var(--brand-primary)] focus:ring-2 focus:ring-green-100";

export function InquiryForm({ publicId, active }: InquiryFormProps) {
  return <form action={submitPublicInquiry} className="grid gap-4 rounded-3xl bg-white p-6 shadow-sm"><input type="hidden" name="publicId" value={publicId} /><input type="hidden" name="idempotencyKey" value={randomUUID()} /><label className="hidden" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><div><h2 className="text-xl font-bold">{active ? "Interested in this property?" : "Continue your property search"}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{active ? "Send your details and the operator will respond within one operating hour." : "Share your details and the operator will create a fresh requirement for similar active properties."}</p></div><label className="grid gap-2 text-sm font-semibold">Name<input required name="fullName" className={inputClass} /></label><label className="grid gap-2 text-sm font-semibold">Phone<input required name="phone" placeholder="+919876500000" className={inputClass} /></label><label className="grid gap-2 text-sm font-semibold">Email <span className="font-normal text-slate-400">optional</span><input name="email" type="email" className={inputClass} /></label><label className="grid gap-2 text-sm font-semibold">Message <span className="font-normal text-slate-400">optional</span><textarea name="message" maxLength={1000} className={`${inputClass} min-h-24`} /></label><label className="flex items-start gap-3 text-sm leading-5"><input required name="consent" type="checkbox" className="mt-1" /><span>I consent to being contacted about my property search.</span></label>{active ? <div className="grid gap-2 sm:grid-cols-2"><button name="intent" value="INTERESTED" className="rounded-xl bg-[var(--brand-primary)] px-4 py-3 font-semibold text-white">I&apos;m interested</button><button name="intent" value="QUESTION" className="rounded-xl border border-slate-300 px-4 py-3 font-semibold">Ask a question</button><button name="intent" value="CREATE_REQUIREMENT" className="rounded-xl border border-slate-300 px-4 py-3 font-semibold sm:col-span-2">Create my requirement</button></div> : <button name="intent" value="CREATE_REQUIREMENT" className="rounded-xl bg-[var(--brand-primary)] px-4 py-3 font-semibold text-white">Create my requirement</button>}</form>;
}

